version: 2
  test:
  override:
    - echo "overrideing tests"
    - ant -lib lib/ Build: 
        timeout: 600

deployment:
  production:
    branch: master
    commands:
      - ant -f build.xml -lib lib/ deployCode        
